/**
 * Project Euler Problem 12: Highly divisible triangular number
 * 
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * 
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 */

#include <iostream>
#include <cmath>

auto count_divisors(int n) -> int {
  auto divisors { 1 };
  auto count    { 0 };

  // Count factors of 2
  while (n % 2 == 0) {
    n /= 2;
    count++;
  }
  divisors *= (count + 1);

  // Count factors of odd numbers
  for (auto i{ 3 }; i * i <= n; i += 2) {
    count = 0;

    while (n % i == 0) {
      n /= i;
      count++;
    }
    divisors *= (count + 1);
  }

  // If n is a prime number greater than 2
  if (n > 2)
    divisors *= 2;

  return divisors;
}

auto main() -> int {
  constexpr auto t{ 500 };

  auto n { 1 };
  auto p { 0 };

  while (true) {
    if (n % 2 == 0)
      p = count_divisors(n / 2) * count_divisors(n + 1);
    else
      p = count_divisors(n) * count_divisors((n + 1) / 2);

    if (p > t)
      break;

    n++;
  }

  const auto triangle{ n * (n + 1) / 2 };

  std::cout << triangle << std::endl;

  return 0;
}
