/**
 * Project Euler Problem 12: Highly divisible triangular number
 * 
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * 
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 */

#include <iostream>
#include <cmath>

auto count_divisors(const int& n) -> int {
  const auto sqrtn { std::sqrt(n) };
  auto       count { 0 };

  for (auto i{ 1 }; i <= sqrtn; i++)
    if (n % i == 0) {
      // If divisors are equal, count only one
      if (n / i == i)
        count++;
      else
        count += 2;
    }

  return count;
}

auto main() -> int {
  constexpr auto target{ 500 };

  auto n        { 1 };
  auto triangle { 0 };
  auto divisors { 0 };

  while (divisors <= target) {
    triangle += n;
    divisors  = count_divisors(triangle);
    n++;
  }

  std::cout << triangle << std::endl;

  return 0;
}