/**
 * Project Euler Problem 12: Highly divisible triangular number
 * 
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * 
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 */

#include <iostream>
#include <cmath>
#include <vector>

auto primeFactors(int n) -> std::vector<int> {
  auto factors  { std::vector<int>{} };
  auto exponent { 0 };

  const auto oddLimit{ std::sqrt(n) };

  // Count factors of 2
  while (n % 2 == 0) {
    n /= 2;
    exponent++;
  }
  if (exponent > 0)
    factors.push_back(exponent);

  // Count factors of odd numbers
  for (auto i{ 3 }; i <= oddLimit; i += 2) {
    exponent = 0;

    while (n % i == 0) {
      n /= i;
      exponent++;
    }
    if (exponent > 0)
      factors.push_back(exponent);
  }

  // If n is a prime number greater than 2
  if (n > 2)
    factors.push_back(1);

  return factors;
}

auto countDivisors(const int& n) -> int {
  auto factors  { primeFactors(n) };
  auto divisors { 1 };

  for (const auto& factor : factors)
    divisors *= (factor + 1);

  return divisors;
}

auto main() -> int {
  constexpr auto target{ 500 };

  auto n       { 1 };
  auto product { 0 };

  while (true) {
    if (n % 2 == 0)
      product = countDivisors(n / 2) * countDivisors(n + 1);
    else
      product = countDivisors(n) * countDivisors((n + 1) / 2);

    if (product > target)
      break;

    n++;
  }

  const auto triangle{ n * (n + 1) / 2 };

  std::cout << triangle << std::endl;

  return 0;
}