/**
 * Project Euler Problem 45: Triangular, pentagonal, and hexagonal
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *
 * Triangle   T_n=n(n+1)/2  1, 3, 6, 10, 15, ...
 * Pentagonal	P_n=n(3n-1)/2	1, 5, 12, 22, 35, ...
 * Hexagonal	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
 *
 * It can be verified that T_{285} = P_{165} = H_{143} = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

#include <iostream>
#include <cmath>

auto hexagonal(const long long& n) -> long long {
  return n * (2 * n - 1);
}

auto isPentagonal(const long long& number) -> bool {
  const auto n{ (std::sqrt(24 * number + 1) + 1) / 6 };

  return (n == static_cast<long long>(n));
}

auto main() -> int {
  for (auto i{ 144LL };; i++) {
    const auto hex{ hexagonal(i) };

    if (isPentagonal(hex)) {
      std::cout << hex << std::endl;
      break;
    }
  }

  return 0;
}