/**
 * Project Euler Problem 45: Triangular, pentagonal, and hexagonal
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *
 * Triangle   T_n=n(n+1)/2  1, 3, 6, 10, 15, ...
 * Pentagonal	P_n=n(3n-1)/2	1, 5, 12, 22, 35, ...
 * Hexagonal	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
 *
 * It can be verified that T_{285} = P_{165} = H_{143} = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

#include <iostream>
#include <unordered_set>

auto triangle(long long n) -> long long {
  return (n * (n + 1) / 2);
}

auto pentagonal(long long n) -> long long {
  return (n * (3 * n - 1) / 2);
}

auto hexagonal(long long n) -> long long {
  return (n * (2 * n - 1));
}

auto main() -> int {
  constexpr auto max{ 100'000LL };

  auto triangles   { std::unordered_set<long long>{} };
  auto pentagonals { std::unordered_set<long long>{} };
  auto hexagonals  { std::unordered_set<long long>{} };

  for (auto n{ 1LL }; n <= max; n++) {
    triangles.insert(triangle(n));
    pentagonals.insert(pentagonal(n));
    hexagonals.insert(hexagonal(n));
  }

  for (const auto& t : triangles)
    if (t > 40755 && pentagonals.find(t) != pentagonals.end() && hexagonals.find(t) != hexagonals.end()) {
      std::cout << t << std::endl;
      break;
    }

  return 0;
}