/**
 * Project Euler Problem 45: Triangular, pentagonal, and hexagonal
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *
 * Triangle   T_n=n(n+1)/2  1, 3, 6, 10, 15, ...
 * Pentagonal	P_n=n(3n-1)/2	1, 5, 12, 22, 35, ...
 * Hexagonal	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
 *
 * It can be verified that T_{285} = P_{165} = H_{143} = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

#include <iostream>

auto triangle(const long long& n) -> long long {
  return (n * (n + 1) / 2);
}

auto pentagonal(const long long& n) -> long long {
  return (n * (3 * n - 1) / 2);
}

auto hexagonal(const long long& n) -> long long {
  return (n * (2 * n - 1));
}

auto isTriangle(const long long& number) -> bool {
  const auto n{ static_cast<long long>(std::sqrt(2 * number)) };

  return (triangle(n) == number || triangle(n + 1) == number);
}

auto main() -> int {
  for (auto i{ 144 }, j{ 166 };;) {
    const auto hex  { hexagonal(i) };
    const auto pent { pentagonal(j) };

    if (hex == pent) {
      if (isTriangle(hex)) {
        std::cout << hex << std::endl;
        break;
      }

      i++; j++;
    }
    else if (hex < pent)
      i++;
    else
      j++;
  }

  return 0;
}