/**
 * Project Euler Problem 61: Cyclical figurate numbers
 * 
 * Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
 *
 * Triangle	 	  P_{3,n}=n(n+1)/2	 	1, 3, 6, 10, 15, ...
 * Square       P_{4,n}=n2	 	      1, 4, 9, 16, 25, ...
 * Pentagonal	 	P_{5,n}=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
 * Hexagonal	 	P_{6,n}=n(2n-1)	 	  1, 6, 15, 28, 45, ...
 * Heptagonal	 	P_{7,n}=n(5n-3)/2	 	1, 7, 18, 34, 55, ...
 * Octagonal	 	P_{8,n}=n(3n-2)	 	  1, 8, 21, 40, 65, ...
 *
 * The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
 *
 * 1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
 * 2. Each polygonal type: triangle (P_{3,127}=8128), square (P_{4,91}=8281), and pentagonal (P_{5,44}=2882), is represented by a different number in the set.
 * 3. This is the only set of 4-digit numbers with this property.
 *
 * Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
 */

#include <iostream>
#include <vector>
#include <algorithm>

auto figurateNumbers(const int& s) -> std::vector<int> {
  auto numbers{ std::vector<int>{} };

  for (auto n{ 1 };; n++) {
    const auto number{ n * ((s - 2) * n - (s - 4)) / 2 };

    if (number < 1000)
      continue;
    else if (number > 9999)
      break;

    numbers.push_back(number);
  }

  return numbers;
}

auto dfs(const int& node, const int& type, std::vector<int>& path, std::vector<int>& pathType, const std::vector<std::vector<int>>& graph, const std::vector<std::vector<int>>& typeGraph) -> bool {
  path.push_back(node);
  pathType.push_back(type);

  if (path.size() == 6) {
    if (path[0] / 100 == path.back() % 100)
      return true;

    path.pop_back();
    pathType.pop_back();

    return false;
  }

  for (auto i{ 0 }; i < graph[node].size(); i++) {
    auto next     { graph[node][i] };
    auto nextType { typeGraph[node][i] };

    if (std::find(pathType.begin(), pathType.end(), nextType) != pathType.end())
      continue;
    else if (dfs(next, nextType, path, pathType, graph, typeGraph))
      return true;
  }

  path.pop_back();
  pathType.pop_back();

  return false;
}

auto main() -> int {
  auto numbers{ std::vector<std::vector<int>>(6) };

  for (auto s{ 3 }; s <= 8; s++)
    numbers[s - 3] = figurateNumbers(s);

  auto graph     { std::vector<std::vector<int>>(10000) };
  auto typeGraph { std::vector<std::vector<int>>(10000) };

  for (auto s{ 0 }; s < 6; s++)
    for (const auto& number : numbers[s])
      for (auto s2{ 0 }; s2 < 6; s2++) {
        if (s2 == s)
          continue;

        for (const auto& number2 : numbers[s2])
          if (number % 100 == number2 / 100) {
            graph[number].push_back(number2);
            typeGraph[number].push_back(s2);
          }
      }

  auto path     { std::vector<int>{} };
  auto pathType { std::vector<int>{} };

  for (const auto& number : numbers[5])
    if (dfs(number, 5, path, pathType, graph, typeGraph))
      break;

  auto sum{ 0 };

  for (const auto& number : path)
    sum += number;

  std::cout << sum << std::endl;

  return 0;
}