/**
 * Project Euler Problem 44: Pentagon numbers
 * 
 * Pentagonal numbers are generated by the formula, P_n=n(3n-1)/2. The first ten pentagonal numbers are:
 * 
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * 
 * It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference, 70 - 22 = 48, is not pentagonal.
 * 
 * Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal and D = |P_k - P_j| is minimized; what is the value of D?
 */

#include <iostream>
#include <vector>
#include <set>
#include <limits>
#include <cmath>
#include <thread>
#include <mutex>
#include <algorithm>

inline auto pentagonal(const int& n) -> int {
  return (n * (3 * n - 1) / 2);
}

inline auto isPentagonal(const int& num, const std::set<int>& pentagonalNumbers) -> bool {
  return (pentagonalNumbers.count(num) > 0);
}

auto calculateD(const int& start, const int& end, const std::vector<int>& pentagonalNumbersList, const std::set<int>& pentagonalNumbersSet, std::mutex& mtx, int& D) -> void {
  auto localD{ std::numeric_limits<int>::max() };

  for (auto i{ start }; i < end; i++)
    for (auto j{ i + 1 }; j < 3000; j++) {
      const auto diff{ pentagonalNumbersList[j] - pentagonalNumbersList[i] };

      if (isPentagonal(diff, pentagonalNumbersSet)) {
        const auto sum{ pentagonalNumbersList[i] + pentagonalNumbersList[j] };

        if (isPentagonal(sum, pentagonalNumbersSet))
          localD = std::min(localD, diff);
      }
    }

  std::lock_guard<std::mutex> lock(mtx);
  D = std::min(D, localD);
}

auto main() -> int {
  auto pentagonalNumbersList { std::vector<int>{} };
  auto pentagonalNumbersSet  { std::set<int>{} };

  for (auto i{ 1 }; i <= 3000; i++) {
    const auto pentNum{ pentagonal(i) };

    pentagonalNumbersList.push_back(pentNum);
    pentagonalNumbersSet.insert(pentNum);
  }

  const auto threadCount { std::thread::hardware_concurrency() };
  auto       threads     { std::vector<std::thread>(threadCount) };
  auto       D           { std::numeric_limits<int>::max() };
  auto       mtx         { std::mutex{} };

  for (auto i{ 0u }; i < threadCount; i++) {
    const auto start { i * 3000 / threadCount };
    const auto end   { (i + 1) * 3000 / threadCount };

    threads[i] = std::thread(calculateD, start, end, std::ref(pentagonalNumbersList), std::ref(pentagonalNumbersSet), std::ref(mtx), std::ref(D));
  }

  for (auto& thread : threads)
    thread.join();

  std::cout << D << std::endl;

  return 0;
}