/**
 * Project Euler Problem 44: Pentagon numbers
 * 
 * Pentagonal numbers are generated by the formula, P_n=n(3n-1)/2. The first ten pentagonal numbers are:
 * 
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * 
 * It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference, 70 - 22 = 48, is not pentagonal.
 * 
 * Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal and D = |P_k - P_j| is minimized; what is the value of D?
 */

#include <iostream>
#include <vector>
#include <set>
#include <limits>
#include <cmath>

auto pentagonal(const int& n) -> int {
  return (n * (3 * n - 1) / 2);
}

auto isPentagonal(int num, const std::set<int>& pentagonalNumbers) -> bool {
  return (pentagonalNumbers.count(num) > 0);
}

auto main() -> int {
  auto pentagonalNumbersList { std::vector<int>{} };
  auto pentagonalNumbersSet  { std::set<int>{} };

  for (auto i{ 1 }; i <= 3000; i++) {
    const auto pentNum{ pentagonal(i) };

    pentagonalNumbersList.push_back(pentNum);
    pentagonalNumbersSet.insert(pentNum);
  }

  auto D{ std::numeric_limits<int>::max() };

  for (auto i{ 0 }; i < 3000; i++)
    for (auto j{ i + 1 }; j < 3000; j++) {
      const auto sum  { pentagonalNumbersList[i] + pentagonalNumbersList[j] };
      const auto diff { pentagonalNumbersList[j] - pentagonalNumbersList[i] };

      if (isPentagonal(sum, pentagonalNumbersSet) && isPentagonal(diff, pentagonalNumbersSet))
        D = std::min(D, diff);
    }

  std::cout << D << std::endl;

  return 0;
}