/**
 * Project Euler Problem 2: Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <iostream>

auto main() -> int {
  constexpr auto limit{ 4000000 };

  auto sum { 0 };
  auto a   { 2 };
  auto b   { 8 };

  while (a <= limit) {
    sum += a;

    const auto c{ 4 * b + a };

    a = b;
    b = c;
  }

  std::cout << sum << std::endl;

  return 0;
}